### ISSUE TITLE
subreddit_stats AssertionError

### ISSUE THREAD

**Issue by psdtwk** [praw-dev/prawtools#25]
This error is becoming more common. This log for /r/Texas. The same error happens with I run a report for /r/Eagles (year), and /r/ultrahardcore (all). 

Thanks for any help you can offer.

---
```
subreddit_stats -R subreddit_stats -u USERNAME -p PASSWORD -vvv -t month
Enter subreddit name: texas
You chose to analyze this subreddit: texas
Logging in
DEBUG: Fetching submissions
DEBUG: Found 446 submissions
DEBUG: Processing Submitters
DEBUG: Processing Commenters on 446 submissions
Traceback (most recent call last):
  File "/usr/local/bin/subreddit_stats", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/prawtools/stats.py", line 572, in main
    srs.process_commenters()
  File "/Library/Python/2.7/site-packages/prawtools/stats.py", line 241, in process_commenters
    skipped = submission.replace_more_comments()
  File "/Library/Python/2.7/site-packages/praw/objects.py", line 1122, in replace_more_comments
    new_comments = item.comments(update=False)
  File "/Library/Python/2.7/site-packages/praw/objects.py", line 700, in comments
    return self._continue_comments(update)
  File "/Library/Python/2.7/site-packages/praw/objects.py", line 683, in _continue_comments
    assert len(self.children) == 1 and self.id == self.children[0]
AssertionError
```

**Comment by bboe** [comment]
See: https://www.reddit.com/r/redditdev/comments/2tlzxl/praw_assertion_errors_on_replace_more_comments/

**Comment by psdtwk** [comment]
Great, thanks!
