### ISSUE TITLE
TypeError while processing password

### ISSUE THREAD

**Issue by wxv** [praw-dev/prawtools#30]
I am using python 3.3, which I believe is supported from what I can tell in setup.py. I get the following error when running `subreddit_stats`:

```
Username: user
Traceback (most recent call last):
  File "c:\python33\lib\runpy.py", line 160, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python33\lib\runpy.py", line 73, in _run_code
    exec(code, run_globals)
  File "C:\Python33\Scripts\subreddit_stats.exe\__main__.py", line 9, in <module
>
  File "c:\python33\lib\site-packages\prawtools\stats.py", line 554, in main
    srs.login(options.user, options.pswd)
  File "c:\python33\lib\site-packages\prawtools\stats.py", line 107, in login
    self.reddit.login(user, pswd)
  File "<decorator-gen-51>", line 2, in login
  File "c:\python33\lib\site-packages\praw\decorators.py", line 78, in wrap
    return function(*args, **kwargs)
  File "c:\python33\lib\site-packages\praw\__init__.py", line 1450, in login
    .encode('ascii', 'ignore'))
  File "c:\python33\lib\getpass.py", line 104, in win_getpass
    msvcrt.putwch(c)
TypeError: must be a unicode character, not int
```

**Comment by wtchen** [comment]
Are you able to get it to work at all? This tool should not be working
since August, when the reddit API went OAuth only...

I have a pull request in to add OAuth support, but it appears it's a bit
buggy. Hopefully someone can help iron out the issues and get this tool
working....

**Comment by wxv** [comment]
No, it does not work at all. If I understand correctly, OAuth is used with a third party, and I am only interested in `top_submitters` and `top_commenters` anyway.

**Comment by wtchen** [comment]
If you were trying to login, it simply won't work. You'll have to change
the code to work around it for now. If you want, you can play with my pull
request from a year ago.

**Comment by bboe** [comment]
The login method has been removed in the latest master, thus this issue is no longer applicable.
